dist: xenial
language: node_js
node_js: '10.22.0'
sudo: false
branches:
  only:
  - master
cache:
  directories:
  - node_modules
install:
- npm install
script:
- printf '%s\n' "APIKEY=$APIKEY" "AUTHDOMAIN=${AUTHDOMAIN}" "DATABASEURL=$DATABASEURL" "PROJECTID=${PROJECTID}" "STORAGEBUCKET=$STORAGEBUCKET" "MESSAGINGSENDERID=${MESSAGINGSENDERID}" "MEASUREMENTID=${MEASUREMENTID}" >.env
- npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: false
  local-dir: build
  on:
    branch: master
